apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-admin-demo-ingress
  name: spring-boot-admin-demo-ingress
spec:
  ports:
    - port: 8080
  selector:
    app: spring-boot-admin-demo-ingress

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-admin-demo-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-admin-demo-ingress
    spec:
      imagePullSecrets: 
      - name: landa-biggeryun-secret
      containers:
      - name: spring-boot-admin-demo-ingress
        image: harbor.biggerk8s.landaudev.com/landa-mas/spring-boot-admin:latest
#        image: harbor.k8s.landaudev.com/demo/spring-boot-admin
        ports:
        - containerPort: 8080
        resources:
          limits:
            #cpu: "1"             #限制pod申请最大的cpu数量为1个cpu
            memory: 3072Mi        #申请内存最大值 3G
          requests:
            #cpu: "0.5"           #pod申请的cpu数量为0.5个cpu
            memory: 2048Mi        #申请内存的最小值 2G
        env: 
          - name: JAVA_OPTS
            value: -Deureka.client.serviceUrl.defaultZone=http://10.100.10.94:30001/eureka/

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-boot-admin-demo-ingress
spec:
  rules:
  - host: spring-boot-admin-demo-ingress.biggerk8s.landacloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: spring-boot-admin-demo-ingress
          servicePort: 8080

