spring: 
  profiles:
    active: @activatedProperties@ #开发过程中可以指定配置环境，实际请使用后面的配置，以便构建使用指定配置构建代码包
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: spring-boot-admin
  security:
    user:
      name: admin
      password: landa
  boot:
    admin:
      ui:
        title: 微应用管理
      notify:
        mail:
          to: #发送给谁 
          - lin.wu@landasoft.com
          - victor.su@landasoft.com
          from: lin.wu@landasoft.com #是谁发送出去的
#邮件通知
  mail:
    host: smtp.exmail.qq.com
    port: 25
    username: lin.wu@landasoft.com
    password: Wly@2018503#客户端授权码hLcaeRBkmzkTaHXe
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
#显示被管理应用的版本号      
info:
  version: @project.version@
 