server:
  port: 8080
  
spring:
  profiles:
    active: dev   # @activatedProperties@ 开发过程中可以指定配置环境，实际请使用后面的配置，以便构建使用指定配置构建代码包
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: SpringBootAdmin
  security:
    user:
      name: admin
      password: landa
  boot:
    admin:
      ui:
        title: 微应用管理

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  