eureka: 
  instance:
    metadata-map:
      user.name: admin
      user.password: landa
    easeRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
#    ip-address: 127.0.0.1
    prefer-ip-address: true
#    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl: 
      defaultZone: http://admin:landa@127.0.0.1:8761/eureka/